name: Gradle Build

on:
  push:
    # Will do a superset of this to release master
    branches-ignore:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Java
        uses: actions/setup-java@v1
        with:
          version: 11

      - name: Build
        run: ./gradlew build

      # TODO Upload test results
